# Generated by Django 2.0 on 2019-02-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='search_tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='myapp.Tag'),
        ),
    ]
