# Generated by Django 2.0 on 2019-02-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190226_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='desciption',
            new_name='description',
        ),
    ]
