# Generated by Django 2.0 on 2019-02-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190226_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(default='no description yet', max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='no title yet', max_length=64),
        ),
    ]
